extends Node2D

# TODO: Falta afegir les possibles peces que l'operari pot anar alternant? o son les unexpected_pieces?
@export var expected_piece: PackedScene # Expected piece generation for this machine
@export var unexpected_pieces: Array[PackedScene] # Unexpected pieces generated by "error"
@export var worker: Worker

var unexpected_piece_active = false # Si hi ha una peca unexpected no en generem més

func spawn_piece():
	var piece
	if should_spawn_unexpected_piece():
		var random_index = randi() % unexpected_pieces.size()
		piece = unexpected_pieces[random_index].instantiate() as Piece
		
		unexpected_piece_active = true
	else:
		piece = expected_piece.instantiate() as Piece	
	
	piece.connect("pressed_piece", _on_unexpected_piece_removed) # Conectar señal para detectar cuando la pieza es eliminada
	if unexpected_piece_active:
		worker.handle_unexpected_piece()
	$"Cinta/Cinta int".add_child(piece)
	
func should_spawn_unexpected_piece() -> bool:
	return not unexpected_piece_active and randf() < 0.20 # 20% of probability to generate an unexpected piece

# Se llama cuando una pieza inesperada es eliminada de la cinta
func _on_unexpected_piece_removed(piece: Piece):
	# TODO: cal mirar si la peça es del grup de les unexpected, segurament segons el nom de expected_piece name o aixi.
	# De fet la propipa peca ens pot dir si es o no expected potser, marcantla amb piece.unexpected per exemple?
	worker._on_removed_unexpected_pieces()  
	piece.queue_free()
	unexpected_piece_active = false # Permitir que se genere otra pieza inesperada en el futuro
	
func _on_timer_timeout() -> void:
	spawn_piece()
	
