extends Node2D

# TODO: Falta afegir les possibles peces que l'operari pot anar alternant? o son les unexpected_pieces?
@export var expected_piece: PackedScene # Expected piece generation for this machine
@export var unexpected_pieces: Array[PackedScene] # Unexpected pieces generated by "error"

var unexpected_piece_active = false # Controla si hay una pieza inesperada en la cinta


func spawn_piece():
	if not unexpected_piece_active and should_spawn_unexpected_piece():
		spawn_unexpected_piece()
		# The worker has to take action(or not)
		$Worker.handle_unexpected_piece()
		unexpected_piece_active = true
	else:
		spawn_expected_piece()
	
func should_spawn_unexpected_piece() -> bool:
	return randf() < 0.20 # 20% of probability to generate an unexpected piece

# Spawns the expected piece and adds it to the conveyor belt
func spawn_expected_piece() -> void:
	var piece = expected_piece.instantiate() as Piece	
	$"Cinta/Cinta int".add_child(piece)

# Spawns a random unexpected piece and adds it to the conveyor belt
func spawn_unexpected_piece() -> void:
	var random_index = randi() % unexpected_pieces.size()
	var piece = unexpected_pieces[random_index].instantiate() as Piece
	$"Cinta/Cinta int".add_child(piece)
	piece.connect("tree_exited", _on_unexpected_piece_removed) # Conectar señal para detectar cuando la pieza es eliminada

# Se llama cuando una pieza inesperada es eliminada de la cinta
func _on_unexpected_piece_removed():
	unexpected_piece_active = false # Permitir que se genere otra pieza inesperada en el futuro
	
# Called when the node enters the scene tree for the first time.
func _ready() -> void:
	pass

# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(_delta: float) -> void:
	pass

func _on_timer_timeout() -> void:
	spawn_piece()
